// Public Suffix List lookups: which part of a domain is a public suffix
// (com, co.uk, github.io) and which is the registrable domain someone owns
// (example.co.uk, evil.github.io). The rules come from
// public/data/public-suffix.json, generated by scripts/refresh-public-suffix.mjs
// and shipped as a data asset rather than inside the JS bundle, so it's
// loaded once with loadPublicSuffixList(). Until it has loaded (or where
// chrome.runtime isn't available, as in plain unit tests) every lookup falls
// back to "the last label is the suffix", which is what Cluster did before.
//
// Algorithm: https://github.com/publicsuffix/list/wiki/Format#formal-algorithm

export interface PublicSuffixData {
  /** Last label → comma-joined rules ending in that label, ASCII (punycode). */
  rules: Record<string, string>;
}

let rulesByLastLabel: Map<string, Set<string>> | null = null;

export function setPublicSuffixRules(data: PublicSuffixData | null): void {
  if (!data) {
    rulesByLastLabel = null;
    return;
  }
  const map = new Map<string, Set<string>>();
  for (const [label, joined] of Object.entries(data.rules)) {
    map.set(label, new Set(joined.split(",").filter(Boolean)));
  }
  rulesByLastLabel = map;
}

export function isPublicSuffixListLoaded(): boolean {
  return rulesByLastLabel !== null;
}

function isPublicSuffixData(value: unknown): value is PublicSuffixData {
  if (!value || typeof value !== "object") return false;
  const rules = (value as { rules?: unknown }).rules;
  return Boolean(rules) && typeof rules === "object" && Object.values(rules as object).every((v) => typeof v === "string");
}

/** Loads the bundled list once. Safe to call repeatedly and from anywhere:
 * it never throws, and outside an extension context it just does nothing. */
let loading: Promise<boolean> | null = null;
export function loadPublicSuffixList(): Promise<boolean> {
  if (rulesByLastLabel) return Promise.resolve(true);
  if (typeof chrome === "undefined" || !chrome.runtime?.getURL) return Promise.resolve(false);
  loading ??= (async () => {
    try {
      const response = await fetch(chrome.runtime.getURL("data/public-suffix.json"));
      const data: unknown = await response.json();
      if (!isPublicSuffixData(data)) return false;
      setPublicSuffixRules(data);
      return true;
    } catch {
      return false;
    } finally {
      loading = null;
    }
  })();
  return loading;
}

function normalize(domain: string): string {
  return domain.trim().toLowerCase().replace(/\.$/, "");
}

/** How many trailing labels of `labels` form the public suffix. */
function suffixLabelCount(labels: string[]): number {
  const rules = rulesByLastLabel?.get(labels[labels.length - 1]);
  if (!rules) return 1; // the default rule "*": the last label alone
  let longest = 1;
  for (let i = 0; i < labels.length; i++) {
    const candidate = labels.slice(i).join(".");
    const count = labels.length - i;
    // An exception rule wins over everything and makes its parent the suffix.
    if (rules.has(`!${candidate}`)) return count - 1;
    const parent = labels.slice(i + 1).join(".");
    if (rules.has(candidate) || (parent && rules.has(`*.${parent}`))) longest = Math.max(longest, count);
  }
  return longest;
}

/** The public suffix of `domain`: "co.uk" for "mail.example.co.uk". */
export function publicSuffix(domain: string): string {
  const labels = normalize(domain).split(".").filter(Boolean);
  if (labels.length === 0) return "";
  return labels.slice(labels.length - suffixLabelCount(labels)).join(".");
}

/** The registrable domain: the public suffix plus one label, e.g.
 * "example.co.uk" for "mail.example.co.uk". Null when `domain` is itself a
 * public suffix (or empty), since nobody can register it. */
export function registrableDomainOf(domain: string): string | null {
  const labels = normalize(domain).split(".").filter(Boolean);
  if (labels.length === 0) return null;
  const suffixCount = suffixLabelCount(labels);
  if (labels.length <= suffixCount) return null;
  return labels.slice(labels.length - suffixCount - 1).join(".");
}
